
package com.traveliko.platform.ws.siteminder;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.0.13
 * 2017-07-25T16:33:31.467+05:00
 * Generated source version: 3.0.13
 * 
 */
public final class SiteConnectService_SiteConnectServicePort_Client {

    private static final QName SERVICE_NAME = new QName("https://www.siteminder.com.au:443/siteconnect", "SiteConnectService");

    private SiteConnectService_SiteConnectServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = SiteConnectService_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        SiteConnectService_Service ss = new SiteConnectService_Service(wsdlURL, SERVICE_NAME);
        SiteConnectService port = ss.getSiteConnectServicePort();  
        
        {
        System.out.println("Invoking hotelResNotifRQ...");
        com.traveliko.platform.ws.siteminder.OTAHotelResNotifRQ _hotelResNotifRQ_otaHotelResNotifRQ = null;
        com.traveliko.platform.ws.siteminder.OTAHotelResNotifRS _hotelResNotifRQ__return = port.hotelResNotifRQ(_hotelResNotifRQ_otaHotelResNotifRQ);
        System.out.println("hotelResNotifRQ.result=" + _hotelResNotifRQ__return);


        }
        {
        System.out.println("Invoking hotelAvailNotifRQ...");
        com.traveliko.platform.ws.siteminder.OTAHotelAvailNotifRQ _hotelAvailNotifRQ_otaHotelAvailNotifRQ = null;
        com.traveliko.platform.ws.siteminder.MessageAcknowledgementType _hotelAvailNotifRQ__return = port.hotelAvailNotifRQ(_hotelAvailNotifRQ_otaHotelAvailNotifRQ);
        System.out.println("hotelAvailNotifRQ.result=" + _hotelAvailNotifRQ__return);


        }
        {
        System.out.println("Invoking hotelRateAmountNotifRQ...");
        com.traveliko.platform.ws.siteminder.OTAHotelRateAmountNotifRQ _hotelRateAmountNotifRQ_otaHotelRateAmountNotifRQ = null;
        com.traveliko.platform.ws.siteminder.MessageAcknowledgementType _hotelRateAmountNotifRQ__return = port.hotelRateAmountNotifRQ(_hotelRateAmountNotifRQ_otaHotelRateAmountNotifRQ);
        System.out.println("hotelRateAmountNotifRQ.result=" + _hotelRateAmountNotifRQ__return);


        }
        {
        System.out.println("Invoking hotelAvailRQ...");
        com.traveliko.platform.ws.siteminder.OTAHotelAvailRQ _hotelAvailRQ_otaHotelAvailRQ = null;
        com.traveliko.platform.ws.siteminder.OTAHotelAvailRS _hotelAvailRQ__return = port.hotelAvailRQ(_hotelAvailRQ_otaHotelAvailRQ);
        System.out.println("hotelAvailRQ.result=" + _hotelAvailRQ__return);


        }

        System.exit(0);
    }

}
