package com.traveliko.platform.ws.siteminder;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.13
 * 2017-07-25T16:33:31.582+05:00
 * Generated source version: 3.0.13
 * 
 */
@WebServiceClient(name = "SiteConnectService", 
                  wsdlLocation = "file:siteconnect.wsdl",
                  targetNamespace = "https://www.siteminder.com.au:443/siteconnect") 
public class SiteConnectService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("https://www.siteminder.com.au:443/siteconnect", "SiteConnectService");
    public final static QName SiteConnectServicePort = new QName("https://www.siteminder.com.au:443/siteconnect", "SiteConnectServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:siteconnect.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SiteConnectService_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:siteconnect.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SiteConnectService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SiteConnectService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SiteConnectService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SiteConnectService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SiteConnectService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SiteConnectService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns SiteConnectService
     */
    @WebEndpoint(name = "SiteConnectServicePort")
    public SiteConnectService getSiteConnectServicePort() {
        return super.getPort(SiteConnectServicePort, SiteConnectService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SiteConnectService
     */
    @WebEndpoint(name = "SiteConnectServicePort")
    public SiteConnectService getSiteConnectServicePort(WebServiceFeature... features) {
        return super.getPort(SiteConnectServicePort, SiteConnectService.class, features);
    }

}
